import React, { useState } from 'react';
import type { ProjectBlueprint } from '../types/mentor';
import { X, Copy, Check, Printer, FileText } from 'lucide-react';

interface ExportModalProps {
  blueprint: ProjectBlueprint;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ blueprint, onClose }) => {
  const [copied, setCopied] = useState(false);

  const generateMarkdownBrief = (): string => {
    return `# 🚀 Hackathon Project Brief: ${blueprint.projectTitle || 'Hackathon Mentor Project'}

## 1. Project Summary
- **Domain**: ${blueprint.domain || 'N/A'}
- **Problem Source**: ${blueprint.problemSource || 'Self-created'}
- **Target Audience**: ${blueprint.targetUser || 'General Users'}
- **Problem Statement**: ${blueprint.problemStatement || 'Defined during stage 1.'}
- **Root Cause**: ${blueprint.rootCause || 'Manual inefficiencies and slow processes.'}
- **Unique Value Proposition (UVP)**: "${blueprint.uvp || 'Fast AI-driven solution.'}"

---

## 2. System Architecture & Tech Stack
- **Frontend**: ${blueprint.techStack.frontend}
- **Backend**: ${blueprint.techStack.backend}
- **Database**: ${blueprint.techStack.database}
- **AI Model**: ${blueprint.techStack.aiModel}
- **Cloud Hosting**: ${blueprint.techStack.cloud}
- **Authentication**: ${blueprint.techStack.auth}

### Architecture Overview
${blueprint.architectureOverview || 'Modular decoupled Client-Server architecture.'}

### System Modules
${(blueprint.modules.length > 0 ? blueprint.modules : ['1. Auth', '2. Core Engine', '3. Export']).map(m => `- ${m}`).join('\n')}

### Database Schema Structure
\`\`\`sql
${blueprint.databaseSchema || `Users (id, email) \nProjects (id, title, blueprint_json)`}
\`\`\`

---

## 3. Feasibility & MVP Scope
### Essential Features (Must Have for Demo)
${(blueprint.essentialFeatures.length > 0 ? blueprint.essentialFeatures : ['Core user flow', 'AI processing']).map(f => `- [x] ${f}`).join('\n')}

### Optional Post-Hackathon Scope
${(blueprint.optionalFeatures.length > 0 ? blueprint.optionalFeatures : ['Social sharing', 'Voice AI']).map(o => `- [ ] ${o}`).join('\n')}

---

## 4. Pitch Script (3–5 Minutes)
- **Opening Hook**: ${blueprint.pitchScript.openingHook || 'Imagine solving a daily problem instantly...'}
- **Problem**: ${blueprint.pitchScript.problem || 'Existing tools fail to provide real-time guidance.'}
- **Solution**: ${blueprint.pitchScript.solution || 'Our AI-powered platform provides stage-by-stage guidance.'}
- **Why Existing Solutions Fail**: ${blueprint.pitchScript.whyExistingFails || 'They are complex and expensive.'}
- **Technology Used**: ${blueprint.pitchScript.techUsed || `Built with ${blueprint.techStack.frontend} & ${blueprint.techStack.aiModel}.`}
- **Market Potential & Future Scope**: ${blueprint.pitchScript.marketPotential || 'Massive student developer adoption.'}
- **Closing Statement**: ${blueprint.pitchScript.closingStatement || 'Thank you!'}

### 30-Second Elevator Pitch
> "${blueprint.elevatorPitch || 'An AI hackathon mentor guiding students from idea to winning presentation.'}"

---

## 5. Judge Defense Q&A Bank
${(blueprint.judgeQA.length > 0 ? blueprint.judgeQA : [
  { question: "Why this problem?", recommendedAnswer: "High validated user demand.", proTip: "Focus on user impact." }
]).map((q, idx) => `### Q${idx + 1}: ${q.question}
- **Answer**: ${q.recommendedAnswer}
- **Pro Tip**: ${q.proTip}
`).join('\n')}

---

## 6. SWOT Analysis & Innovation Scorecard
- **Overall Innovation Score**: ${blueprint.innovationScore.overallScore.toFixed(1)} / 10
- **Strengths**: ${blueprint.swot.strengths.join(', ') || 'Fast setup, clean UX'}
- **Weaknesses**: ${blueprint.swot.weaknesses.join(', ') || 'Limited hackathon time'}
- **Opportunities**: ${blueprint.swot.opportunities.join(', ') || 'High judge appeal'}
- **Threats**: ${blueprint.swot.threats.join(', ') || 'API latency'}

---
*Generated by Hackathon Mentor AI*
`;
  };

  const markdownContent = generateMarkdownBrief();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={{
      position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(0,0,0,0.8)', backdropFilter: 'blur(10px)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      zIndex: 2000, padding: '20px'
    }}>
      <div className="glass-panel" style={{
        width: '100%', maxWidth: '850px', maxHeight: '90vh',
        display: 'flex', flexDirection: 'column', overflow: 'hidden'
      }}>
        {/* Header */}
        <div style={{
          padding: '14px 20px', background: 'rgba(15, 23, 42, 0.9)',
          borderBottom: '1px solid var(--border-color)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between'
        }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--cyan)', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FileText size={20} /> Export Hackathon Project Brief
          </h3>
          <button className="btn btn-outline btn-sm" onClick={onClose}>
            <X size={16} />
          </button>
        </div>

        {/* Markdown Body Preview */}
        <div style={{ flex: 1, padding: '20px', overflowY: 'auto', background: 'rgba(10, 14, 23, 0.95)' }}>
          <pre style={{
            fontFamily: 'var(--font-mono)', fontSize: '0.8rem', color: '#cbd5e1',
            whiteSpace: 'pre-wrap', lineHeight: '1.6'
          }}>
            {markdownContent}
          </pre>
        </div>

        {/* Footer Actions */}
        <div style={{
          padding: '12px 20px', background: 'rgba(15, 23, 42, 0.9)',
          borderTop: '1px solid var(--border-color)',
          display: 'flex', justifyContent: 'flex-end', gap: '10px'
        }}>
          <button className="btn btn-outline" onClick={handlePrint}>
            <Printer size={16} /> Print / Save PDF
          </button>
          <button className="btn btn-cyan" onClick={handleCopy}>
            {copied ? <Check size={16} /> : <Copy size={16} />}
            {copied ? 'Copied to Clipboard!' : 'Copy Markdown'}
          </button>
        </div>
      </div>
    </div>
  );
};
