import React, { useState, useEffect } from 'react';
import { Presentation, Play, Pause, RotateCcw, Sparkles, ArrowRight, Download, Eye, FileText, ChevronLeft, ChevronRight, Edit3 } from 'lucide-react';

export default function PitchBuilder({ projectState, setProjectState, onNext }) {
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
  const [isPlayingScript, setIsPlayingScript] = useState(false);
  const [timerSeconds, setTimerSeconds] = useState(90);
  const [activeTabMode, setActiveTabMode] = useState('slides'); // 'slides' or 'teleprompter'
  const [fontSize, setFontSize] = useState('1.2rem');

  useEffect(() => {
    let interval = null;
    if (isPlayingScript && timerSeconds > 0) {
      interval = setInterval(() => {
        setTimerSeconds(prev => prev - 1);
      }, 1000);
    } else if (timerSeconds === 0) {
      setIsPlayingScript(false);
    }
    return () => clearInterval(interval);
  }, [isPlayingScript, timerSeconds]);

  const handleAutoGenerateDeck = () => {
    const title = projectState.title || "Our Project";
    const prob = projectState.problemStatement || "Users face manual friction and high complexity.";
    const sol = projectState.solution || "An automated AI copilot streamlining end-to-end workflows.";
    const nov = projectState.novelty || "Real-time predictive AI engine with sub-200ms latency.";
    const stack = projectState.techStack?.join(', ') || "React 18 & Node.js";

    const generated = [
      { id: 1, title: 'The Problem Hook', content: prob },
      { id: 2, title: 'Our Solution: ' + title, content: sol },
      { id: 3, title: 'Secret Sauce & USP', content: nov },
      { id: 4, title: 'Technical Architecture', content: `Engineered using ${stack}. Built for real-time scale and offline resilience.` },
      { id: 5, title: 'Feasibility & Impact', content: 'Reduces operational overhead by 80% and delivers verifiable ROI within 30 days.' },
      { id: 6, title: 'Market Opportunity', content: 'Addressing a multi-billion dollar high-growth market.' },
      { id: 7, title: 'Team & Roadmap', content: 'Built by Team HackPilots. Next: Enterprise API integrations and production deployment.' }
    ];

    const script = `🚀 [0:00 - 0:20 HOOK]\n"Did you know target users suffer every day because ${prob}?\n\n💡 [0:20 - 0:50 SOLUTION & DEMO]\nMeet ${title}! ${sol} In our live demo today, you'll see how easy it is to solve this problem.\n\n⚙️ [0:50 - 1:15 ARCHITECTURE]\nOur secret sauce is ${nov}, powered by ${stack}.\n\n🏆 [1:15 - 1:30 CLOSING]\nWe cut operational friction by 80%. We are ready to launch ${title}!"`;

    setProjectState(prev => ({
      ...prev,
      slides: generated,
      elevatorScript: script
    }));
  };

  const handleSlideChange = (field, value) => {
    setProjectState(prev => {
      const updated = [...prev.slides];
      updated[currentSlideIndex] = { ...updated[currentSlideIndex], [field]: value };
      return { ...prev, slides: updated };
    });
  };

  const handleAddSlide = () => {
    const newId = projectState.slides.length + 1;
    const newSlide = { id: newId, title: `Slide ${newId}: Custom Topic`, content: 'Enter custom slide bullet points here...' };
    setProjectState(prev => ({
      ...prev,
      slides: [...prev.slides, newSlide]
    }));
    setCurrentSlideIndex(projectState.slides.length);
  };

  const handleDeleteSlide = (indexToDelete) => {
    if (projectState.slides.length <= 1) return;
    setProjectState(prev => ({
      ...prev,
      slides: prev.slides.filter((_, idx) => idx !== indexToDelete)
    }));
    setCurrentSlideIndex(prev => Math.max(0, prev - 1));
  };

  const currentSlide = projectState.slides[currentSlideIndex] || { title: 'Slide', content: 'Content' };

  const formatTime = (secs) => {
    const mins = Math.floor(secs / 60);
    const remaining = secs % 60;
    return `${mins}:${remaining < 10 ? '0' : ''}${remaining}`;
  };

  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
      {/* Banner */}
      <div className="glass-card glow-purple" style={{ padding: '32px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyBetween: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{
              padding: '10px 14px',
              borderRadius: '12px',
              background: 'rgba(139, 92, 246, 0.2)',
              color: '#a78bfa',
              border: '1px solid rgba(139, 92, 246, 0.3)'
            }}>
              <Presentation size={28} />
            </div>
            <div>
              <span className="badge badge-purple">Stage 4 of 6</span>
              <h2 style={{ fontSize: '1.8rem', marginTop: '4px' }}>Pitch Deck Builder & Elevator Script</h2>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '10px' }}>
            <button
              onClick={() => setActiveTabMode('slides')}
              className={`btn ${activeTabMode === 'slides' ? 'btn-primary' : 'btn-secondary'}`}
            >
              <Presentation size={16} /> 7-Slide Deck
            </button>
            <button
              onClick={() => setActiveTabMode('teleprompter')}
              className={`btn ${activeTabMode === 'teleprompter' ? 'btn-cyan' : 'btn-secondary'}`}
            >
              <Play size={16} /> 90-Sec Teleprompter
            </button>
          </div>
        </div>
      </div>

      {activeTabMode === 'slides' ? (
        /* Slides Mode */
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))', gap: '24px' }}>
          {/* Left Column: Visual Slide Preview Carousel */}
          <div className="glass-card" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span className="badge badge-purple">Slide {currentSlideIndex + 1} of {projectState.slides.length}</span>
              <button onClick={handleAutoGenerateDeck} className="btn btn-ghost" style={{ fontSize: '0.82rem', color: '#a78bfa' }}>
                <Sparkles size={14} /> Auto-Generate All Slides
              </button>
            </div>

            {/* Slide Stage Presentation Card */}
            <div style={{
              background: 'linear-gradient(135deg, #0f172a 0%, #070a14 100%)',
              border: '2px solid rgba(139, 92, 246, 0.4)',
              borderRadius: '16px',
              padding: '36px 28px',
              minHeight: '280px',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              boxShadow: '0 12px 35px rgba(0, 0, 0, 0.6)',
              position: 'relative'
            }}>
              <span style={{ fontSize: '0.75rem', color: '#64748b', position: 'absolute', top: '16px', left: '20px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                HACKATHON PITCH DECK
              </span>
              <h3 style={{ fontSize: '1.6rem', color: '#f8fafc', marginBottom: '16px' }} className="gradient-text-purple">
                {currentSlide.title}
              </h3>
              <p style={{ fontSize: '1.05rem', color: '#cbd5e1', lineHeight: '1.7', whiteSpace: 'pre-wrap' }}>
                {currentSlide.content}
              </p>
            </div>

            {/* Controls */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <button
                disabled={currentSlideIndex === 0}
                onClick={() => setCurrentSlideIndex(prev => prev - 1)}
                className="btn btn-secondary"
              >
                <ChevronLeft size={18} /> Previous
              </button>
              <div style={{ display: 'flex', gap: '6px' }}>
                {projectState.slides.map((_, idx) => (
                  <div
                    key={idx}
                    onClick={() => setCurrentSlideIndex(idx)}
                    style={{
                      width: '10px',
                      height: '10px',
                      borderRadius: '50%',
                      background: idx === currentSlideIndex ? '#8b5cf6' : 'rgba(255, 255, 255, 0.2)',
                      cursor: 'pointer'
                    }}
                  />
                ))}
              </div>
              <button
                disabled={currentSlideIndex === projectState.slides.length - 1}
                onClick={() => setCurrentSlideIndex(prev => prev + 1)}
                className="btn btn-secondary"
              >
                Next <ChevronRight size={18} />
              </button>
            </div>
          </div>

          {/* Right Column: Slide Content Editor */}
          <div className="glass-card" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Edit3 size={20} color="#06b6d4" />
              <h3 style={{ fontSize: '1.2rem', margin: 0 }}>Edit Slide Content</h3>
            </div>

            <div>
              <label style={{ fontSize: '0.85rem', color: '#94a3b8', marginBottom: '6px', display: 'block' }}>
                Slide Title
              </label>
              <input
                type="text"
                className="input-field"
                value={currentSlide.title}
                onChange={(e) => handleSlideChange('title', e.target.value)}
              />
            </div>

            <div>
              <label style={{ fontSize: '0.85rem', color: '#94a3b8', marginBottom: '6px', display: 'block' }}>
                Slide Bullet Points / Main Message
              </label>
              <textarea
                className="textarea-field"
                rows={6}
                value={currentSlide.content}
                onChange={(e) => handleSlideChange('content', e.target.value)}
              />
            </div>

            <div style={{ marginTop: 'auto', paddingTop: '10px' }}>
              <button
                onClick={onNext}
                className="btn btn-emerald"
                style={{ width: '100%', padding: '14px', fontSize: '1rem' }}
              >
                Proceed to AI Judge Simulator
                <ArrowRight size={18} />
              </button>
            </div>
          </div>
        </div>
      ) : (
        /* Teleprompter Mode */
        <div className="glass-card" style={{ padding: '28px', display: 'flex', flexDirection: 'column', gap: '24px' }}>
          {/* Teleprompter Controls Bar */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
              <button
                onClick={() => setIsPlayingScript(!isPlayingScript)}
                className={`btn ${isPlayingScript ? 'btn-secondary' : 'btn-cyan'}`}
                style={{ padding: '12px 24px', fontSize: '1rem' }}
              >
                {isPlayingScript ? <Pause size={18} /> : <Play size={18} />}
                {isPlayingScript ? 'Pause Practice' : 'Start 90s Speech Practice'}
              </button>

              <button
                onClick={() => {
                  setIsPlayingScript(false);
                  setTimerSeconds(90);
                }}
                className="btn btn-ghost"
              >
                <RotateCcw size={16} /> Reset
              </button>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
              <div>
                <span style={{ fontSize: '0.8rem', color: '#94a3b8', marginRight: '8px' }}>Font Size:</span>
                <button onClick={() => setFontSize('1rem')} className="btn btn-ghost" style={{ padding: '4px 8px' }}>A-</button>
                <button onClick={() => setFontSize('1.3rem')} className="btn btn-ghost" style={{ padding: '4px 8px' }}>A</button>
                <button onClick={() => setFontSize('1.6rem')} className="btn btn-ghost" style={{ padding: '4px 8px' }}>A+</button>
              </div>

              <div style={{
                fontSize: '1.6rem',
                fontFamily: 'var(--font-mono)',
                fontWeight: 700,
                color: timerSeconds < 15 ? '#f43f5e' : '#22d3ee',
                background: 'rgba(15, 23, 42, 0.8)',
                padding: '6px 16px',
                borderRadius: '10px',
                border: '1px solid rgba(255,255,255,0.1)'
              }}>
                ⏱️ {formatTime(timerSeconds)}
              </div>
            </div>
          </div>

          {/* Teleprompter Display Box */}
          <div className="teleprompter-box" style={{ fontSize }}>
            {projectState.elevatorScript}
          </div>

          {/* Edit Script Box */}
          <div>
            <label style={{ fontSize: '0.85rem', color: '#94a3b8', marginBottom: '6px', display: 'block' }}>
              Edit Elevator Pitch Script Text
            </label>
            <textarea
              className="textarea-field"
              rows={4}
              value={projectState.elevatorScript}
              onChange={(e) => setProjectState({ ...projectState, elevatorScript: e.target.value })}
            />
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <button
              onClick={onNext}
              className="btn btn-emerald"
              style={{ padding: '14px 28px', fontSize: '1rem' }}
            >
              Proceed to AI Judge Simulator
              <ArrowRight size={18} />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
